### ISSUE TITLE
Your npmignore shouldn't ignore the test file

### ISSUE THREAD

**Issue by khoomeister** [coatue/react2angular#1]
Either that or tsconfig.json should be amended.

![image](https://cloud.githubusercontent.com/assets/681288/23776604/169437e2-04e4-11e7-9082-6605c3db8c18.png)

**Comment by bcherny** [comment]
Can separate it into 2 tsconfigs, but why are you recompiling the lib instead of using the js and dts files?

**Comment by khoomeister** [comment]
not recompiling, it just appears in my vscode while working on another project
