### ISSUE TITLE
[Feature] Using propTypes instead of declaring array of bindings

### ISSUE THREAD

**Issue by mribichich** [coatue/react2angular#2]
Hi there, awesome project, I wanted to ask you maybe providing another way of declaring the bindings.

instead of passing them as the second argument in the definition, maybe if the propTypes are declare you could use that instead.

That way is much easier to maintain and the binding are next to the component, instead of the angular definition.

``` javascript
import { Component } from 'react'

class MyComponent extends Component {
  static propTypes = {
    fooBar: React.PropTypes.string.isRequired,
    baz: React.PropTypes.string.isRequired
  };

  render() {
    return <div>
      <p>FooBar: {this.props.fooBar}</p>
      <p>Baz: {this.props.baz}</p>
    </div>
  }
}
```

``` javascript
import { react2angular } from 'react2angular'

angular
  .module('myModule', [])
  .component('myComponent', react2angular(MyComponent))
```

That way in the library instead of doing: 
`bindings: fromPairs(bindingNames.map(_ => [_, '<'])),` 

you could do something like:
`bindings: fromPairs(Object.keys(MyComponent.propTypes).map(_ => [_, '<']),`

You could support both ways, propTypes being the default and if the array of bindings is declare you would use that one instead overriding propTypes.

Thanks!

**Comment by bcherny** [comment]
Hey @mribichich, that's a great idea! We don't have an immediate use case for this, but feel free to submit a PR and I'll be sure to get it merged.

**Comment by mribichich** [comment]
Alright great, I'll do it! thanks

**Comment by beshanoe** [comment]
But some people don't use PropTypes at all in TypeScript. They use generics syntax which looks way more natural to me.

```
import { Component } from 'react'

interface IMyComponentProps {
  fooBar: string;
  baz: string;
}

interface IMyComponentState {
  optional?: any
}

class MyComponent extends Component<IMyComponentProps, IMyComponentState> {
  render() {
    return <div>
      <p>FooBar: {this.props.fooBar}</p>
      <p>Baz: {this.props.baz}</p>
    </div>
  }
}
```

 I think PropTypes support should be optional and not be in README in the first place
