### ISSUE TITLE
[Bug] class_1 is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by mribichich** [coatue/react2angular#3]
Hi there, The controller that's being return doesn't have the `$inject` definition so in strict di angular fails to bootstrap.

The `class extends NgComponent` should provide the static $inject with `$element`.

I'll send you a PR too if you want to.

thanks

**Comment by bcherny** [comment]
Thanks for the bug report! Published 1.0.6 - let me know if that fixes your issue.

**Comment by mribichich** [comment]
great! it works now! thanks
